volumes:
  mongo:
  minio:

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      - MINIO_ACCESS_KEY=astrrstr
      - MINIO_SECRET_KEY=astascrtxcta
    command: server /data --console-address ":9001"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=deno